# Checkov configuration
# https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html

# Only scan Terraform files
framework:
  - terraform

# Compact output
compact: true

# Skip checks that don't apply to this project
skip-check:
  # CKV_GIT_1: Repo is intentionally public (open-source IaC)
  - CKV_GIT_1
  # CKV_GIT_5: Solo developer - cannot require 2 approvals
  - CKV_GIT_5
  
# Check severity threshold
# soft-fail: true  # Don't fail the build (set in workflow)
